version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3"  # latest stable

python:
  install:
    # Documentation build requirements. Regenerate with:
    #   $ poetry export --format='requirements.txt' --only=docs > docs/requirements.txt
    - requirements: docs/requirements.txt
    # Install this distribution.
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py

formats:
  - pdf
